# Generated by Django 5.0.3 on 2024-04-24 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Número de identificación')),
                ('name', models.CharField(max_length=200, verbose_name='Profesor')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('cellphone', models.CharField(max_length=20, verbose_name='Teléfono celular')),
                ('city', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('state', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='Activo', max_length=200, verbose_name='Estado')),
                ('picture', models.ImageField(upload_to='pictures/', verbose_name='Foto del profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('period', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cohorte del semestre')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('ending_date', models.DateField(verbose_name='Fecha de finalización')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Materia')),
                ('nrc', models.CharField(max_length=200, verbose_name='NRC')),
                ('credits', models.PositiveIntegerField(verbose_name='Número de créditos')),
                ('type', models.CharField(choices=[('CURRICULAR', 'Curricular'), ('ELECTIVA', 'Electiva')], max_length=200, verbose_name='Tipo')),
                ('syllabus', models.FileField(error_messages={'invalid_extension': 'Por favor, suba el archivo en formato .PDF'}, upload_to='syllabuses/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Syllabus')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('ending_date', models.DateField(verbose_name='Fecha de finalización')),
                ('modality', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=200, verbose_name='Modalidad de la materia')),
                ('num_sessions', models.PositiveIntegerField(verbose_name='Cantidad de sesiones')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_status', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=200, verbose_name='Estado del contrato')),
                ('contact_preparation_date', models.DateField(verbose_name='Fecha de elaboración')),
                ('id_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AcademicProgrammingApplication.teacher', verbose_name='Profesor asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Viatic',
            fields=[
                ('transport', models.BooleanField(verbose_name='Transporte')),
                ('accommodation', models.BooleanField(verbose_name='Alojamiento')),
                ('viatic', models.BooleanField(verbose_name='Viático')),
                ('id_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AcademicProgrammingApplication.teacher', verbose_name='Profesor asociado')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_file', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('path', models.FileField(default='BaseProgramming.xlsx', upload_to='archivos/')),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Programa')),
                ('faculty', models.CharField(max_length=200, verbose_name='Facultad academica')),
                ('director', models.CharField(max_length=200, verbose_name='Director de programa')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de matricula')),
                ('type', models.CharField(choices=[('ESPECIALIZACIÓN', 'Especialización'), ('MAESTRÍA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=200, verbose_name='Tipo de programa')),
                ('modality', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=200, verbose_name='Modalidad del programa')),
                ('duration', models.CharField(max_length=200, verbose_name='Duración del programa')),
                ('curriculum', models.FileField(error_messages={'invalid_extension': 'Por favor, suba el archivo en formato .PDF'}, upload_to='curriculums/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Curriculum del programa')),
                ('semesters', models.ManyToManyField(to='AcademicProgrammingApplication.semester', verbose_name='Semestres asociados')),
                ('subjects', models.ManyToManyField(to='AcademicProgrammingApplication.subject', verbose_name='Materias de programas')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Número de sesión')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio de la clase')),
                ('ending_date', models.DateTimeField(verbose_name='Fecha de finalización de la clase')),
                ('modality', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=200, verbose_name='Modalidad de la clase')),
                ('classroom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Salón de clase')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace de la plataforma virtual')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicProgrammingApplication.teacher', verbose_name='Profesor asociado')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademicProgrammingApplication.subject', verbose_name='Materia asociada')),
            ],
        ),
    ]
