# Generated by Django 5.0.3 on 2024-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('student_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID del estudiante')),
                ('id_type', models.CharField(max_length=100, verbose_name='Tipo de ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='Enviar correo electrónico'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='AcademicProgrammingApplication.student', verbose_name='Estudiantes'),
        ),
    ]
