# Generated by Django 5.0.3 on 2024-04-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='username',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
