# Generated by Django 5.0.3 on 2024-03-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='Activo', max_length=200, verbose_name='Estado'),
        ),
    ]
