# Generated by Django 5.0.3 on 2024-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0002_teacher_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('ESPECIALIZACIÓN', 'Especialización'), ('MAESTRÍA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=200, verbose_name='Tipo de programa'),
        ),
    ]
