# Generated by Django 5.0.3 on 2024-04-18 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0003_alter_program_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('student_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID del estudiante')),
                ('id_type', models.CharField(max_length=100, verbose_name='Tipo de ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='AcademicProgrammingApplication.subject', verbose_name='Materia')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='AcademicProgrammingApplication.teacher', verbose_name='Profesor de la materia')),
            ],
        ),
    ]
