# Generated by Django 5.0.3 on 2024-04-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0003_viatic_id_alter_viatic_id_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatic',
            name='viatic_status',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('NO_ENVIADO', 'No Enviado')], default='NO_ENVIADO', max_length=200, verbose_name='Estado del viático'),
        ),
    ]
