# Generated by Django 5.0.3 on 2024-04-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='Enviar correo electrónico'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='AcademicProgrammingApplication.student', verbose_name='Estudiantes'),
        ),
    ]
