# Generated by Django 5.0.3 on 2024-04-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0004_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='path',
            field=models.FileField(default='ProgramacionBase.xlsx', upload_to='archivos/'),
        ),
    ]
