# Generated by Django 5.0.3 on 2024-04-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0004_viatic_viatic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatic',
            name='viatic_status',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('NO_ENVIADA', 'No Enviada')], default='NO_ENVIADO', max_length=200, verbose_name='Estado del viático'),
        ),
    ]
