# Generated by Django 5.0.3 on 2024-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0005_archivo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='path',
            field=models.FileField(default='BaseProgramming.xlsx', upload_to='archivos/'),
        ),
    ]
