# Generated by Django 5.0.3 on 2024-04-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0006_alter_archivo_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivo',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='nombre_archivo',
            new_name='name_file',
        ),
    ]
