# Generated by Django 5.0.3 on 2024-04-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicProgrammingApplication', '0002_remove_file_user_file_username'),
        ('AcademicProgrammingApplication', '0006_student_class_send_email_class_students'),
    ]

    operations = [
    ]
