from .login import *
from .sign_up import *
from .logout import *
from .error_404 import *
from .academic_management import *
from .assign_teacher import *
from .base_screen import *
from .subject_detail import *
from .edit_info_class import *
from .role_management import *
