from .Class import Class
from .Contract import Contract
from .Program import Program
from .Semester import Semester
from .Subject import Subject
from .Teacher import Teacher
from .Viatic import Viatic
from .User import User
from .Role import Role
from .PlanningProposal import PlanningProposal
from .Student import Student
